### ISSUE TITLE
Nice! :) / Some suggestions

### ISSUE THREAD

**Issue by simonihmig** [onechiporenko/ember-bootstrap-modals-manager#1]
Hi @onechiporenko,

just saw your addon listed in EmberWeekly, and just want quickly drop a note that I like this! :)

We used a similar approach in an app we built, but that was more limited to what we needed there (mainly `confirm`). I always thought that something like this would be useful, but also that `ember-bootstrap` should not be concerned with that, rather stay focused on the basic UI components, and other addons can build something on top of it. Nice that you found the time for this! :) 

Some little suggestions:

* it seems to me when you `ember install ember-bootstrap-modals-manager`, it will not install `ember-bootstrap` along with it, right? You can either add it to `dependencies` (rather than `devdependencies`), or maybe better add a default blueprint that calls `this.addAddonToProject('ember-bootstrap')` (so users can control their e-b version in their app's `package.json`). I use the latter approach here for example: https://github.com/kaliber5/ember-bootstrap/blob/master/blueprints/ember-bootstrap/index.js#L144
* maybe apply `type="primary"` to the "main" button in the footer?

**Comment by onechiporenko** [comment]
Hi, @simonihmig. Thanks for your feedback and suggestions!
I'll add `type="primary"` and I'll do something with `ember-bootstrap` dependency. Idea with blueprint looks very good for me.

**Comment by onechiporenko** [comment]
@simonihmig, could you please check if it's all what need to be done to auto-install `ember-bootstrap` if it's not installed?
https://github.com/onechiporenko/ember-bootstrap-modals-manager/pull/2
Thanks
