### ISSUE TITLE
Issue with imports

### ISSUE THREAD

**Issue by jstys** [onechiporenko/ember-bootstrap-modals-manager#12]
This might be user-error but I'm on ember 3.15 currently and have tried unsuccessfully using ember-bootstrap-modals-manager v3.2.0 and 3.3.0.  The error I'm getting is 

Could not find module `ember-modals-manager-internal/templates/components/modals-container/alert` imported from `ember-bootstrap-modals-manager/components/modals-container/alert`

I have the `<ModalsContainer />` in my `application.hbs` and I'm just attempting to get a hello world example with a simple alert modal to show.

```javascript
@action
showImportAlert() {
    this.modalsManager.alert({title: 'Alert Title', body: 'Alert Body'})
    .then(() => {
      // called after user clicks "Yes" in the modal
    });
}
```

**Comment by basz** [comment]
Are you sure you have `ember-modals-manager-internal` installed? This addon depends on that one... Check your packages.json
