### ISSUE TITLE
custom class

### ISSUE THREAD

**Issue by basz** [onechiporenko/ember-bootstrap-modals-manager#13]
I would like to be able to control a custom class set on the container. Would you accept a PR for that? I think it would be simple enough to support...

My use case:

I need to create an transparent modal for 'working' purposes... Therefore I need to claer backgrounds and add shadows...

![image](https://user-images.githubusercontent.com/143068/78791251-ecf5f080-79af-11ea-905f-96f15c8274f0.png)

vs

![image](https://user-images.githubusercontent.com/143068/78791370-13b42700-79b0-11ea-97c1-f7c67a616438.png)

(manually added a class 'busy-modal')

**Comment by onechiporenko** [comment]
Hello @basz.
Sure. I'm open for PR!
