### ISSUE TITLE
Passing values

### ISSUE THREAD

**Issue by syedkhairi** [onechiporenko/ember-bootstrap-modals-manager#31]
Hiya! Any ideas why I can't pass values? Followed exactly the docs [here](https://onechiporenko.github.io/ember-bootstrap-modals-manager/docs/modals/passing-values).

Using Ember 3.20.5 & ember-bootstrap-modals-manager 4.3.0.

Example for my case:

Template:
```html
<button type="button" {{on "click" (fn showModalWithForm 'YouTube')}}>Add YouTube</button>
```

Controller:
```javascript
@action
showModalWithForm(type) {
	return get(this, 'modalsManager')
	  .show('modal-paste-url', {
		  urlType: type,
		  position: 'center',
		  backdropClose: false,
})
	  .then(formValues => {
	    console.log(formValues)
	  })
	  .catch(() => {
	    // modal is closed without submit
	  });
}
```

Component .hbs:
```html
<BsModal as |modal|>
  <modal.header @title="Add {{@urlType}} link"/>
  <modal.body>
    <BsForm novalidate
      @model={{this.formData}}
      @onSubmit={{fn this.confirm}}
    as |form|>
      <form.element
        @property="url"
        @label="Link"/>
    </BsForm>
  </modal.body>
  <modal.footer>
    <BsButton
      @onClick={{modal.close}}
      @type="default"
      @defaultText="Cancel"/>
    <BsButton
      @onClick={{modal.submit}}
      @type="success"
      @defaultText="Add"/>
  </modal.footer>
</BsModal>
```

The other properties defined (`position`, `backdropClose`) works, but the property `urlType` not passed on to component. Also installed `ember-modals-manager-internal` not sure what that does - but also doesn't work. 

Any ideas? Thanks

**Comment by onechiporenko** [comment]
Hello, @syedkhairi. It should be `@options.urlType`. There is a mistake in docs :/

**Comment by syedkhairi** [comment]
> Hello, @syedkhairi. It should be `@options.urlType`. There is a mistake in docs :/

That works perfectly! Thank you so much!
