### ISSUE TITLE
Issue with modalsManager.process on v5.0 release

### ISSUE THREAD

**Issue by dreamsbond** [onechiporenko/ember-bootstrap-modals-manager#38]
This might be issue using ember-bootstrap-modals-manager v5.0 release, have tried fail rendering process modal with default usage: 

```
  @service()
  modalsManager;

  @action
  showProcessModal() {
    this.modalsManager
      .process({
        bodyComponent: 'custom-process-body',
        headerComponent: 'custom-process-footer',
        footerComponent: 'custom-process-header',
        process: () => new Promise(resolve => setTimeout(resolve(1), 100))
      })
      .then(result => {})
      .catch(error => {});
  }
```

raised an uncaught error

```
Uncaught Error: Assertion Failed: Backdrop element should be in DOM
    at Object.assert (index.js:172)
    at bs-modal.js:512
    at invoke (backburner.js:340)
    at Queue.flush (backburner.js:229)
    at DeferredActionQueues.flush (backburner.js:426)
    at Backburner._end (backburner.js:960)
    at Backburner.end (backburner.js:710)
    at Backburner._runExpiredTimers (backburner.js:1097)
```

**Comment by onechiporenko** [comment]
Hi, @dreamsbond. Did you update some default settings for this addon or ember-bootstrap itself?

**Comment by dreamsbond** [comment]
hi @onechiporenko, the config/optional-feature.js was
````
{
  "application-template-wrapper": false,
  "default-async-observers": true,
  "jquery-integration": false,
  "template-only-glimmer-components": true
}
```

the same situation was found in progress modal as well.

**Comment by onechiporenko** [comment]
Ok. Could you please create a small demo on the ember-twiddle or separated repo? I realy can't get what is going wrong in your case :/

**Comment by syedkhairi** [comment]
Hello,

I encountered the same issue after upgrading everything.

I try to isolate the issue and create a fresh install of ember, ember-bootstrap & ember-bootstrap-modals-manager - error in DOM.

Here's a sample repo: https://github.com/syedkhairi/modal-bootstrap.git

I can't manage to get ember-twiddle working lol

**Comment by onechiporenko** [comment]
HI, @syedkhairi. You forgot to add 
```html
<ModalsContainer></ModalsContainer>
```
to your `application.hbs`

**Comment by syedkhairi** [comment]
Of course! Missed that bit, sorry!

That works for the sample repo above - but I still encountered the issue in my actual project. Trying to isolate one by one but can't figure out what is going on.

<img width="657" alt="CleanShot 2022-05-07 at 13 38 11@2x" src="https://user-images.githubusercontent.com/5096292/167254804-8007daf9-d605-4fa0-b1c5-717589b4403f.png">

"@ember/optional-features": "^2.0.0",
    "@ember/test-helpers": "^2.6.0",
    "@glimmer/component": "^1.0.4",
    "@glimmer/tracking": "^1.0.4",
    "babel-eslint": "^10.1.0",
    "bootstrap": "^5.1.3",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^2.4.1",
    "ember-bootstrap": "^5.1.0",
    "ember-bootstrap-modals-manager": "^5.0.0",
    "ember-cli": "~4.3.0",
    "ember-cli-app-version": "^5.0.0",
    "ember-cli-babel": "^7.26.11",,
    "ember-data": "~4.1.0",

**Comment by onechiporenko** [comment]
Could it be related to https://github.com/kaliber5/ember-bootstrap/issues/1786 ?

**Comment by syedkhairi** [comment]
> Could it be related to [kaliber5/ember-bootstrap#1786](https://github.com/kaliber5/ember-bootstrap/issues/1786) ?

The reply to that issue fixed my issue.

> For the record, as this has been discussed on Discord: I think the problem comes from having different versions of `ember-modifier` in your lockfile:
> 
> > No, there is no fix in the works, as there is likely nothing to be fixed on ember-bootstrap's side. As mentioned earlier,  I assume there might be an issue with different versions of ember-modifier. So either all addons have to be updated to use the latest, or pinned to at least use the same version.  There should be no different versions of the same addon be used in the same app.
> 
> I'll keep this open for visibility, but AFAICT there is nothing to fix here.


One of my add-ons using an old version of ember-modifier. Updating it so all dependencies using the same version of ember-modifier, fixed it.

All good now!

Thank you!
