### ISSUE TITLE
release a new version with latest

### ISSUE THREAD

**Issue by basz** [onechiporenko/ember-bootstrap-modals-manager#51]
hi, v5 does not work without some fixes that are in master. Is a new release possible?

This is problemeatic for when using forms: https://github.com/onechiporenko/ember-bootstrap-modals-manager/compare/v5.0.0...master#diff-4220dfaba3085bebe02d5d39ff0c43bfaefc56150201a4f7a13ad074ea47c1e2R50

thanks!

**Comment by onechiporenko** [comment]
Hi, @basz. 
I've released [v6.0.0-beta.1](https://github.com/onechiporenko/ember-bootstrap-modals-manager/releases/tag/v6.0.0-beta.1). Hope it'll helps.

**Comment by basz** [comment]
awesome. thank you!
