### ISSUE TITLE
docs and demo page give error 404

### ISSUE THREAD

**Issue by Polve** [onechiporenko/ember-bootstrap-modals-manager#78]
It seems like the linked website https://onechiporenko.github.io/ is not deployed/available

Even the links from the ember-bootstrap page are broken: https://www.ember-bootstrap.com/addons/

**Comment by wukongrita** [comment]
Hi @Polve ,

Here is the link:

- Docs: https://onechiporenko.github.io/ember-bootstrap-modals-manager/
- Demo: https://onechiporenko.github.io/ember-bootstrap-modals-manager/#/demo

Hope that help...
